In [362]:
import numpy as np

In [389]:
A = np.mat([
    [3, 4],
    [4, 0]
])

In [390]:
E = np.identity(len(A))

In [391]:
a0 = A[:, 0]

In [392]:
alpha = np.linalg.norm(a0, 2)

In [393]:
v0 = a0 + alpha*np.eye(len(a0), 1)

In [394]:
x = alpha*np.eye(len(a0), 1)

In [395]:
x

array([[5.],
       [0.]])

In [396]:
u = a0 - x

In [398]:
u

matrix([[-2.],
        [ 4.]])

In [397]:
Q = E - 2*((u*u.T)/(u.T*u))
Q*A

matrix([[5. , 2.4],
        [0. , 3.2]])

In [386]:
un = u / np.linalg.norm(u, 2)

In [387]:
Q = (E - 2*un*un.T)

In [388]:
Q*A

matrix([[5.0000000e+00, 2.6000000e+00],
        [4.4408921e-16, 1.8000000e+00]])