In [8]:
import numpy as np
from scipy.stats import entropy

In [9]:
A = np.matrix([
    [0, 1, 0],
    [1/2, 0, 1/2],
    [0, 1/2, 1/2],
])

assert (A.sum(axis=1) == np.ones(A.shape[1])).all()

In [10]:
S, U = np.linalg.eig(A.T)
stationary = np.array(U[:, np.where(np.abs(S - 1.) < 1e-8)[0][0]].flat)
stationary = stationary / np.sum(stationary)

In [11]:
np.round(stationary.astype(float), 3)

array([0.2, 0.4, 0.4])

In [12]:
A**100000

matrix([[0.2, 0.4, 0.4],
        [0.2, 0.4, 0.4],
        [0.2, 0.4, 0.4]])

In [13]:
_ = [print("===", _, "===\n", A**_) for _ in range(10)]

=== 0 ===
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
=== 1 ===
 [[0.  1.  0. ]
 [0.5 0.  0.5]
 [0.  0.5 0.5]]
=== 2 ===
 [[0.5  0.   0.5 ]
 [0.   0.75 0.25]
 [0.25 0.25 0.5 ]]
=== 3 ===
 [[0.    0.75  0.25 ]
 [0.375 0.125 0.5  ]
 [0.125 0.5   0.375]]
=== 4 ===
 [[0.375  0.125  0.5   ]
 [0.0625 0.625  0.3125]
 [0.25   0.3125 0.4375]]
=== 5 ===
 [[0.0625  0.625   0.3125 ]
 [0.3125  0.21875 0.46875]
 [0.15625 0.46875 0.375  ]]
=== 6 ===
 [[0.3125   0.21875  0.46875 ]
 [0.109375 0.546875 0.34375 ]
 [0.234375 0.34375  0.421875]]
=== 7 ===
 [[0.109375  0.546875  0.34375  ]
 [0.2734375 0.28125   0.4453125]
 [0.171875  0.4453125 0.3828125]]
=== 8 ===
 [[0.2734375  0.28125    0.4453125 ]
 [0.140625   0.49609375 0.36328125]
 [0.22265625 0.36328125 0.4140625 ]]
=== 9 ===
 [[0.140625   0.49609375 0.36328125]
 [0.24804688 0.32226562 0.4296875 ]
 [0.18164062 0.4296875  0.38867188]]
