In [1]:
import numpy as np
import pandas as pd

Given the covariance matrix M and eigenvectors u1, u2, and u3

In [20]:
M = np.mat([[91.43,  171.92, 297.99 ],
            [171.92, 373.92, 545.21 ],
            [297.99, 545.21, 1297.26]])

In [21]:
u1 = np.mat([0.22, 0.41, 0.88])
u2 = np.mat([0.25, 0.85, -0.46])
u3 = np.mat([0.94, -0.32, -0.08])

eigenvalues l1, l2, l3

In [28]:
(M*u1.T)/u1.T

matrix([[1603.78636364],
        [1636.37658537],
        [1625.77579545]])

In [29]:
(M*u2.T)/u2.T

matrix([[127.6564    ],
        [129.42988235],
        [127.85565217]])

In [30]:
(M*u3.T)/u3.T

matrix([[  7.54319149],
        [  5.2075    ],
        [-23.2825    ]])

Given the following dataset S, eigenvalues e1, e2, eigenvectors x1, x2 transform the input using PCA

In [31]:
S = np.mat([[1, -1], 
            [0,  1], 
            [-1, 0]])

In [33]:
e1 = 3
e2 = 1

In [51]:
x1 = np.mat([1/np.sqrt(2), -1/np.sqrt(2)])
x2 = np.mat([1/np.sqrt(2),  1/np.sqrt(2)])

subtract the mean from each attrib

In [52]:
# But the means are zero so subtract nothing
print(S[:,0].mean(), S[:,1].mean())

0.0 0.0


In [56]:
transformed = S*x1.T

recover the original data from the primary component

In [66]:
transformed*x1

matrix([[ 1. , -1. ],
        [-0.5,  0.5],
        [-0.5,  0.5]])

λ1=2.5, λ3=1

v1=[ 2 1 -2 ] v2=[ 1 -2 0 ]

and a covariance matrix given by

```
4 1   2 
1 2.5 1 
2 1   5
```

In [70]:
C = np.matrix([[4, 1, 2], 
               [1, 2.5, 1], 
               [2, 1, 5]])

In [71]:
v1 = np.mat([2, 1, -2])
v2 = np.mat([1, -2, 0])

a) What is the value for eigenvalue λ2?

In [75]:
(C*v2.T)/v2.T

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


matrix([[ 2.],
        [ 2.],
        [nan]])

In [76]:
x = np.mat([1, 1, 1])

In [87]:
x*np.hstack([v1.T, v2.T])

matrix([[ 1, -1]])