# SVD - Singular Value Desomposion

(VZD notation: $A \rightarrow X, S \rightarrow \Sigma$)

based on the [https://fenix.tecnico.ulisboa.pt/downloadFile/3779576344458/singular-value-decomposition-fast-track-tutorial.pdf](https://fenix.tecnico.ulisboa.pt/downloadFile/3779576344458/singular-value-decomposition-fast-track-tutorial.pdf)


$X = U \Sigma V^T$

To compute U:

$U = XV \Sigma^{-1}$

In [211]:
import numpy as np

X = np.matrix([[4, 0], 
               [3, -5]])

In [212]:
XTX = X.T*X
print("XTX:\n", XTX)

XTX:
 [[ 25 -15]
 [-15  25]]


Compute the eigenvalues of $X^TX$

In [213]:
from numpy.linalg import eig

eigenvalues, eigenvectors = eig(XTX)

In [214]:
print("eigenvalues:", np.round(eigenvalues))
print("eigenvectors:\n", eigenvectors)

eigenvalues: [40. 10.]
eigenvectors:
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


Create the $\Sigma$ matrix and find the inverse $\Sigma^{-1}$

In [216]:
from numpy.linalg import inv

singularvalues = np.sqrt(eigenvalues)
S = np.diag(singularvalues)
S_inv = inv(S)
print("Σ^-1:\n", S_inv)

Σ^-1:
 [[0.15811388 0.        ]
 [0.         0.31622777]]


From eigenvectors create the matrix $V$

In [217]:
V = eigenvectors
print("V:\n", V)

V:
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


$U=XV\Sigma^{-1}$

In [218]:
U = X*V*inv(S)
print("U:\n", U)

U:
 [[ 0.4472136   0.89442719]
 [ 0.89442719 -0.4472136 ]]


prove that the results match $X = U\Sigma V^T$

In [219]:
print("X:\n", np.round(U*S*V.T, 2))

X:
 [[ 4. -0.]
 [ 3. -5.]]


Reduce the dimension

In [205]:
dims_after_svd = 1

In [220]:
X_s = X*V[:,:dims_after_svd]
print("X' (after dimension reduction):\n", np.round(X_s, 3))

X' (after dimension reduction):
 [[2.828]
 [5.657]]


### Test if the result matches the SKLearn

In [221]:
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=dims_after_svd, n_iter=7)

In [224]:
print(np.round(svd.fit_transform(X), 3))

[[2.828]
 [5.657]]
