In [1]:
import keras

print("Keras version:", keras.__version__)

Using TensorFlow backend.


Keras version: 2.2.4


In [2]:
from string import printable

text = "ahoj vole"
text_tokens = [printable.index(x) + 1 for x in text if x in printable]

In [3]:
print(text)
print(text_tokens)

ahoj vole
[11, 18, 25, 20, 95, 32, 25, 22, 15]


In [4]:
from keras.preprocessing.text import Tokenizer

texts = ["aaaahoj vole",
        "uz je zase rano",
        "vstavej do prace"]

tokenizer = Tokenizer(num_words=None, lower=False, char_level=True, oov_token=True)
tokenizer.fit_on_texts(texts)
texts_tokenized = tokenizer.texts_to_sequences(texts)

In [5]:
from keras.preprocessing.sequence import pad_sequences

# maximum length of arrays of characters
padded_len = 20

# number of characters
num_chars = len(tokenizer.word_index) + 1

texts_tokenized_padded = pad_sequences(texts_tokenized, maxlen=padded_len)
print(texts_tokenized_padded)
print("number of chars:", num_chars)

[[ 0  0  0  0  0  0  0  0  2  2  2  2 11  5  6  3  7  5 12  4]
 [ 0  0  0  0  0 13  8  3  6  4  3  8  2  9  4  3 10  2 14  5]
 [ 0  0  0  0  7  9 15  2  7  4  6  3 16  5  3 17 10  2 18  4]]
number of chars: 19


In [6]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
import numpy as np

categories = ["hovno",
              "ne",
              "ne"]

label_encoder = LabelEncoder()
target = np.array(categories, dtype="str")
target = label_encoder.fit_transform(target)
target = to_categorical(target, num_classes=2)

print(target)

[[1. 0.]
 [0. 1.]
 [0. 1.]]


In [7]:
from keras.layers import Input, Embedding, Dense, Flatten
from keras.regularizers import l2
from keras.optimizers import Adam
from keras.models import Model


# Input
main_input = Input(shape=(padded_len,), dtype='int32')
emb = Embedding(input_dim=num_chars, output_dim=2, input_length=padded_len)(main_input) 

f = Flatten()(emb)
output = Dense(2, activation='softmax')(f)

# Compile model and define optimizer
model = Model(inputs=[main_input], output=[output])
adam = Adam(lr=1e-4, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
model.summary()
model.compile(optimizer=adam, loss='categorical_crossentropy', metrics=['accuracy'])

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 20)                0         
_________________________________________________________________
embedding_1 (Embedding)      (None, 20, 2)             38        
_________________________________________________________________
flatten_1 (Flatten)          (None, 40)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 82        
Total params: 120
Trainable params: 120
Non-trainable params: 0
_________________________________________________________________


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:15: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=[<tf.Tenso..., outputs=[<tf.Tenso...)`
  from ipykernel import kernelapp as app


In [8]:
texts_tokenized_padded

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  2,  2,  2,  2, 11,  5,  6,  3,
         7,  5, 12,  4],
       [ 0,  0,  0,  0,  0, 13,  8,  3,  6,  4,  3,  8,  2,  9,  4,  3,
        10,  2, 14,  5],
       [ 0,  0,  0,  0,  7,  9, 15,  2,  7,  4,  6,  3, 16,  5,  3, 17,
        10,  2, 18,  4]], dtype=int32)

In [9]:
target

array([[1., 0.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [10]:
model.fit(texts_tokenized_padded, target, epochs=100, batch_size=1)

Epoch 1/100
3/3 [==============================] - 0s 80ms/step - loss: 0.6994 - acc: 0.6667
Epoch 2/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6988 - acc: 0.6667
Epoch 3/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6982 - acc: 0.6667
Epoch 4/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6976 - acc: 0.6667
Epoch 5/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6971 - acc: 0.6667
Epoch 6/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6965 - acc: 0.6667
Epoch 7/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6961 - acc: 0.6667
Epoch 8/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6956 - acc: 0.6667
Epoch 9/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6950 - acc: 0.6667
Epoch 10/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6945 - acc: 0.6667
Epoch 11/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6939

3/3 [==============================] - 0s 2ms/step - loss: 0.6534 - acc: 1.0000
Epoch 90/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6530 - acc: 1.0000
Epoch 91/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6524 - acc: 1.0000
Epoch 92/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6519 - acc: 1.0000
Epoch 93/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6513 - acc: 1.0000
Epoch 94/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6509 - acc: 1.0000
Epoch 95/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6504 - acc: 1.0000
Epoch 96/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6498 - acc: 1.0000
Epoch 97/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6492 - acc: 1.0000
Epoch 98/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6488 - acc: 1.0000
Epoch 99/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6481 - ac

In [14]:
# weights for each character in vocabulary
model.layers[1].get_weights()

[array([[ 0.03068077,  0.04111718],
        [-0.0192078 , -0.02749819],
        [ 0.03773568, -0.00578519],
        [ 0.00581718,  0.04050089],
        [-0.0275339 ,  0.010617  ],
        [ 0.05569772,  0.00710094],
        [ 0.02340886,  0.0021414 ],
        [-0.0127705 , -0.01261688],
        [ 0.02951985, -0.03448699],
        [ 0.02420008,  0.02796276],
        [ 0.062594  ,  0.03381588],
        [-0.0277958 , -0.02157798],
        [-0.00395103,  0.03870299],
        [-0.00723388, -0.02038889],
        [-0.03784964, -0.05714012],
        [-0.00364514,  0.02129517],
        [ 0.04001863, -0.0082342 ],
        [ 0.0050469 ,  0.03642355],
        [ 0.02364043, -0.05844093]], dtype=float32)]